export const SIGN_UP_URL = 'http://localhost:4000/auth/signup'
export const GET_PROFILE_URL = 'http://localhost:4000/auth'
export const LOGIN_URL = 'http://localhost:4000/auth/login'
export const ADD_DPF_URL = 'http://localhost:4000/pdf'
export const CREATE_PROJECT_URL = 'http://localhost:4000/projects'
export const GET_ALL_PROJECTS_URL = 'http://localhost:4000/projects/all'
export const EDIT_PROFILE_URL = 'http://localhost:4000/users/edit'
export const VOTE_PROJECTS_URL = 'http://localhost:4000/projects/like'
